#!/bin/bash -e

CONTROL0=$(terraform output -json control-plane | jq -r ' ."kube-control-00"')
CONTROL_VIP=$(terraform output -raw control-plane-vip)
SSH_KEY_PATH=$(terraform output -raw ssh-private-key-path)
SSH_USERNAME=$(terraform output -raw ssh-user)

scp -i $SSH_KEY_PATH $SSH_USERNAME@$CONTROL0:/etc/rancher/k3s/k3s.yaml ~/.kube/config

# Update the downloaded config file to point to the IP of the control plane VIP
sed -i.bak "s/127.0.0.1/${CONTROL_VIP}/" ~/.kube/config
